name: Build release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0 or 3.0.0-alpha.

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        config: [release_rev3, release_rev2, hw_troubleshoot, release_rev3-readonly_msc]

    runs-on: ubuntu-latest
    container: 
      image: shilga/raspberry-pi-pico-gbdk-docker:v0.4

    env:
      BUILDDIR: "build_${{ matrix.config }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Configure CMake
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        CONFARGS=""
        CONF=$(echo ${{ matrix.config }} | cut -d '-' -f1)
        if echo ${{ matrix.config }} | grep -q "readonly_msc"; then
          echo "enable readonly msc"
          CONFARGS="${CONFARGS} -DREADONLY_MSC=1"
        fi
        if [ x"${CONF}" == "xrelease_rev2" ]; then
          echo "Build for config: REV2_LAYOUT"
          cmake --fresh -B ${{ github.workspace }}/${{ env.BUILDDIR }}_${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${CONFARGS} -DREV2_LAYOUT=1

        elif [ x"${CONF}" == "xhw_troubleshoot" ]; then
          echo "Build for config: HW_TROUBLESHOOT"
          cmake --fresh -B ${{ github.workspace }}/${{ env.BUILDDIR }}_${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${CONFARGS} -DHW_TROUBLESHOOT_BUILD=1

        else
          echo "Build for config: default"
          cmake --fresh -B ${{ github.workspace }}/${{ env.BUILDDIR }}_${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${CONFARGS}

        fi

    - name: Build
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        make -C ${{ github.workspace }}/${{ env.BUILDDIR }}_${{ matrix.config }} -j

    - name: Package artifacts
      run: |
        cd ${{ github.workspace }}/${{ env.BUILDDIR }}_${{ matrix.config }}
        tar cvzf ${GITHUB_WORKSPACE}/shawazu-gb-dumper-${{ matrix.config }}-${{ github.ref_name }}.tgz *.bin *.elf *.elf.map *.hex *.uf2

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: shawazu-gb-dumper-${{ matrix.config }}-${{ github.ref_name }}
        path: |
          ${{ github.workspace }}/shawazu-gb-dumper-*-${{ github.ref_name }}.tgz

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: list files
        run: ls

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          draft: false
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: "*.tgz"
